apiVersion: v1
kind: Pod
metadata:
  name: echo-server
spec:
  containers:
    - name: echo-server
      image: gcr.io/containers-1380/echo-server
      ports:
        - containerPort: 8080
          hostPort: 80
      env:        
        - name: PORT
          value: "8080"  
        - name: APPENV
          value: production
  restartPolicy: Always
